import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";

const archivo = localFont({
  src: "./fonts/ArchivoNarrow-VariableFont_wght.ttf",
  variable: "--font-main",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
